/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * <h2><center>&copy; Copyright (c) 2021 STMicroelectronics.
 * All rights reserved.</center></h2>
 *
 * This software component is licensed by ST under BSD 3-Clause license,
 * the "License"; You may not use this file except in compliance with the
 * License. You may obtain a copy of the License at:
 *                        opensource.org/licenses/BSD-3-Clause
 *
 ******************************************************************************
 */


#include "main.h"

#define send
//#define lm335z
//#define ds18b20
#define DHT11
//#define ds18b20_lm335z
//#define ds18b20_lm335z_DHT11


int main(void)
{
clock48Mhz_init();
#ifdef lm335z
	lm335z_init();
#ifdef send
	usart_init();
#endif
	while (1)
	{
		lm335z_start_convert();
	}
#endif

#ifdef ds18b20
	ds18b20_Init_Work();
#ifdef send
	usart_init();
#endif
	while (1)
	{
		sending_data_ds18b20();
	}
#endif

#ifdef ds18b20_lm335z
	ds18b20_Init_Work();
	lm335z_init();
#ifdef send
	usart_init();
#endif
	while (1)
	{
		lm335z_start_convert();
		sending_data_ds18b20();
	}
#endif

#ifdef ds18b20_lm335z_DHT11
	dht11_init();
	ds18b20_Init_Work();
	lm335z_init();
#ifdef send
	usart_init();
#endif
	while (1)
	{
		lm335z_start_convert();
		us_delay(200000); //delay for proper data transmission
		sending_data_ds18b20();
		us_delay(200000); //delay for proper data transmission
		DHT11_real_values();

	}
#endif

#ifdef DHT11
	dht11_init();
#ifdef send
	usart_init();
#endif
	while (1)
	{
		DHT11_real_values();
	}
#endif
}
